### ISSUE TITLE
Error about  TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by Cocofeat** [wentaozhu/AnatomyNet-for-anatomical-segmentation#22]
Hello, doc. Zhu, many thanks for your code, recently I am following your paper of AnatomyNet,  but when I use your code, the error is below, I just changed the data path:
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:/Coco_file/AnatomyNet-for-anatomical-segmentation-master/AnatomyNet-for-anatomical-segmentation-master/src/AnatomyNet.py", line 160, in <module>
    train_data, test_data = process('C:/Coco_file/dataset/pddca18/')
  File "C:/Coco_file/AnatomyNet-for-anatomical-segmentation-master/AnatomyNet-for-anatomical-segmentation-master/src/AnatomyNet.py", line 146, in process
    return getdatamask(train_data+train_dataopt+test_data,  train_masks_data+train_masks_dataopt+test_masks_data,debug=debug), getdatamask(test_dataoff, test_masks_dataoff,debug=debug)
  File "C:/Coco_file/AnatomyNet-for-anatomical-segmentation-master/AnatomyNet-for-anatomical-segmentation-master/src/AnatomyNet.py", line 99, in getdatamask
    img = imfit(img, int(tnz), int(tny), int(tnx)) #zoom(img, (tnz/nz,tny/ny,tnx/nx), order=2, mode='nearest')
  File "C:/Coco_file/AnatomyNet-for-anatomical-segmentation-master/AnatomyNet-for-anatomical-segmentation-master/src/AnatomyNet.py", line 90, in imfit
    retimg[bz:ez, by:ey, bx:ex] = img

It seems the error of resize the img, but I have no idea, Can you help me. Thanks !

**Comment by Cocofeat** [comment]
Sorry for interrupt, I solved it. 
the code line :
retimg[bz:ez, by:ey, bx:ex] = img
should be changed:
retimg[int(bz):int(ez), int(by):int(ey), int(bx):int(ex)] = img
